check typos

diff --git a/.github/workflows/codeql-scan.yml b/.github/workflows/codeql-scan.yml
--- a/.github/workflows/codeql-scan.yml
+++ b/.github/workflows/codeql-scan.yml
@@ -26,6 +26,7 @@ jobs:
         with:
           output_format: cli,sarif
           output_file_path: console,results.sarif
+          framework: terraform
 
       - name: Upload SARIF file
         uses: github/codeql-action/upload-sarif@v2
@@ -38,3 +39,17 @@ jobs:
         if: success() || failure()
         with:
           sarif_file: results.sarif
+
+      # - name: Upload SARIF file to GitHub Security tab
+      #   if: success() || failure()  # Always attempt to upload SARIF
+      #   uses: github/codeql-action/upload-sarif@v2
+      #   with:
+      #     sarif_file: checkov.sarif
+
+      - name: Annotate Parsing Errors
+        if: failure() # Run only if Checkov encountered an error
+        run: |
+          echo "Parsing errors found in Checkov scan, displaying as annotations."
+          grep -i "error" checkov.sarif | while read -r line; do
+            echo "::error::${line}"
+          done
